### PR TITLE
chore: bump dependencies

### PR DESCRIPTION
**Pull request by afuetterer**
I ran `poetry update` on your lockfile. Do you want this monitored by dependabot as well?

### CODE REVIEW

**Comment by provinzkraut** [comment]
@afuetterer it seems that the ruff update has caused some formatting changes which break the tests that check the ruffed output.

**Comment by afuetterer** [comment]
Oh no, damn it. Should I try to fix the tests or you want to stick to the older ruff version for now?

**Comment by provinzkraut** [comment]
Updating the tests would be fine

**Comment by afuetterer** [comment]
Okay, let's see. :)

**Comment by provinzkraut** [comment]
@afuetterer Turns out I was wrong: This is actually a bug. I'll create a fix for that in a different PR

**Comment by afuetterer** [comment]
I see, excellent.

**Pull request merged**
